import type { Metadata } from "next";
import "./globals.css";

import { Press_Start_2P } from "next/font/google";
import { Outfit } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const bitcount = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bitcount",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ahmed Ali - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bitcount.variable} ${outfit.variable}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
